version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/node:14  # Node.js 14 Docker image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Version of Docker
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Docker image
          command: docker build -t your_dockerhub_username/nodejs-sproutly-app .
      - run:
          name: Docker Login to DockerHub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker Image to DockerHub
          command: docker push your_dockerhub_username/nodejs-sproutly-app
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-to-k3s:
    docker:
      - image: circleci/python:3.8  # Choose a basic image for SSH and kubectl
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"
      - run:
          name: Setup KUBECONFIG
          command: |
            ssh -o "StrictHostKeyChecking no" ubuntu@<your-ec2-ip> "mkdir -p /.kube && echo $KUBECONFIG_DATA | base64 --decode > /.kube/config"
      - run:
          name: Deploy to K3s
          command: |
            ssh -o "StrictHostKeyChecking no" ubuntu@<your-ec2-ip> "
              kubectl set image deployment/nodejs-sproutly-app nodejs-sproutly-app=your_dockerhub_username/nodejs-sproutly-app:latest --record
            "

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy-to-k3s:
          requires:
            - build-and-push
