version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/node:14  # Node.js 14 Docker image
    steps:
      - checkout
      - setup_remote_docker: {}
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Docker Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: docker build -t piusiyke/nodejs-sproutly-app .

      - run:
          name: Push Docker Image to DockerHub
          command: docker push piusiyke/nodejs-sproutly-app
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-to-k3s:
    docker:
      - image: circleci/node:14  # Use Node.js 14 for deployment
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:92:44:96:2f:02:e3:2c:7f:53:80:24:af:db:de:3d"
      - run:
          name: Recreate PEM file from CircleCI environment variable
          command: |
            echo "$PEM_KEY" > /home/circleci/main.pem
            chmod 600 /home/circleci/main.pem
      - run:
          name: Setup KUBECONFIG
          command: |
            scp -i /home/ubuntu/main.pem ubuntu@54.82.25.216:/home/ubuntu/kubeconfig.yaml ~/.kube/config
            sed -i 's/127.0.0.1/54.82.25.216/g' ~/.kube/config
            export KUBECONFIG=~/.kube/config
      - run:
          name: Deploy to K3s
          command: |
            ssh -o "StrictHostKeyChecking no" -i /home/ubuntu/main.pem ubuntu@54.82.25.216 "
              kubectl apply -f nodejs-sproutly-app-deployment.yaml
              kubectl apply -f nodejs-sproutly-app-service.yaml
              kubectl set image deployment/nodejs-sproutly-app-deployment nodejs-sproutly-app=piusiyke/nodejs-sproutly-app:latest --record
            "

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy-to-k3s:
          requires:
            - build-and-push

